### PR TITLE
Release: v2022.03.17

### PR DESCRIPTION
**Pull request by tamalsaha**
Signed-off-by: Tamal Saha <tamal@appscode.com>

### CODE REVIEW

**Comment by 1gtm** [comment]
/tagged github.com/voyagermesh/apimachinery
/go github.com/voyagermesh/apimachinery voyagermesh.dev/apimachinery

**Comment by tamalsaha** [comment]
/tagged github.com/voyagermesh/apimachinery
/go github.com/voyagermesh/apimachinery voyagermesh.dev/apimachinery

**Comment by 1gtm** [comment]
/pr https://github.com/voyagermesh/cli/pull/8
/go github.com/voyagermesh/cli voyagermesh.dev/cli 
/pr https://github.com/voyagermesh/haproxy-ingress/pull/46
/go github.com/voyagermesh/haproxy-ingress voyagermesh.dev/haproxy-ingress github.com/appscode/haproxy-ingress

**Comment by 1gtm** [comment]
/ready-to-tag github.com/voyagermesh/cli 16d852a79e5f5f49bd050d8e5f8e1f9b22725b96

**Comment by 1gtm** [comment]
/ready-to-tag github.com/voyagermesh/haproxy-ingress 73961286988897281b781a770b21bbfd2afbe6a7

**Comment by 1gtm** [comment]
/pr https://github.com/voyagermesh/installer/pull/109
/go github.com/voyagermesh/installer voyagermesh.dev/installer

**Comment by 1gtm** [comment]
/ready-to-tag github.com/voyagermesh/installer f9d677aabe2984e3da933abea1902fc244c4b8c9

**Comment by 1gtm** [comment]
/ready-to-tag github.com/voyagermesh/voyager 2150bcd7d9270df588faca40825d9cec20243e09

**Comment by 1gtm** [comment]
/ready-to-tag github.com/voyagermesh/website e202bb1fd36867d2c09b58e0f02bc6d92ef4959a

**Pull request merged**
